# Generated by Django 3.2.9 on 2021-11-24 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0002_rename_materia_model_materia'),
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoBimestreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.CharField(max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='BimestreMateriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Nota')),
                ('media', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Media')),
                ('aluno_bimestre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boletim.alunobimestremodel')),
                ('materia', models.ManyToManyField(to='materia.Materia')),
            ],
        ),
    ]
