# Generated by Django 3.2.9 on 2021-11-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimestremateriamodel',
            name='aluno_bimestre',
        ),
        migrations.AddField(
            model_name='bimestremateriamodel',
            name='aluno_bimestre',
            field=models.ManyToManyField(to='boletim.AlunoBimestreModel'),
        ),
        migrations.AlterField(
            model_name='bimestremateriamodel',
            name='media',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='bimestremateriamodel',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota'),
        ),
    ]
