# Generated by Django 3.2.9 on 2021-11-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletim', '0002_auto_20211124_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimestremateriamodel',
            name='aluno_bimestre',
        ),
        migrations.RemoveField(
            model_name='bimestremateriamodel',
            name='materia',
        ),
    ]
