# Generated by Django 3.2.9 on 2021-11-24 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        ('materia', '0002_rename_materia_model_materia'),
        ('boletim', '0003_auto_20211124_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimestreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.CharField(max_length=4)),
                ('bimestre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BoletimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Media')),
                ('aluno_bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletim.bimestremodel')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.materia')),
            ],
        ),
        migrations.RemoveField(
            model_name='alunobimestremodel',
            name='aluno',
        ),
        migrations.DeleteModel(
            name='BimestreMateriaModel',
        ),
        migrations.DeleteModel(
            name='AlunoBimestreModel',
        ),
    ]
