# Generated by Django 3.2.9 on 2021-11-24 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletim', '0004_auto_20211124_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletimmodel',
            name='media',
        ),
    ]
