# Generated by Django 3.2.9 on 2021-11-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('responsavel', models.CharField(max_length=100)),
                ('telefone_responsavel', models.CharField(max_length=11)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
