# Generated by Django 3.2.9 on 2021-11-20 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materia_Model',
            new_name='Materia',
        ),
    ]
